# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU



GITHUB_KEY: ee4060e8240b700e47fa
GITHUB_SECRET: 450b588cf86f39bdcccc564ea3d36f6635f2cb82

FACEBOOK_KEY: 1898594500408476
FACEBOOK_SECRET: d0e86f16f4eea3f1e81f8885995ac18b


